version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install  Node.js v14 with build in nvm tool
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v14 && nvm use 14 && nvm alias default 14
            node -v
      - run:
          name: Check Node version
          command: node -v
      - restore_cache:
          keys:
            - node_modules_cache_{{ checksum "package-lock.json" }}
      - run: 
          name: Install QuML Library dependencies
          command: cd projects/quml-library &&  npm install --no-progress
      - run:
          name: Install project dependencies
          command: |
            if [ ! -d "node_modules" ]; then
            npm i -f
            fi
      - save_cache:
          key: node_modules_cache_{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Executing test cases
          command: npm run test-lib-ci
      - run:
          name: Install sonar scanner
          command: 'sudo npm install -i -g sonarqube-scanner'
      - run:
          name: Run Sonar scanner
          command: sonar-scanner
      - run:
          name: Publish to NPM
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then
              npm run build-lib && npm pack ./dist/quml-library
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              npm publish project-sunbird-sunbird-quml-player-*
            else
              npm run build-lib && npm pack ./dist/quml-library
            fi